version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: unless-stopped

  app:
    build: .
    expose:
      - "8000"
    volumes:
      - ./backups:/app/backups
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.web.main:app --host 0.0.0.0 --port 8000

  bot:
    build: .
    volumes:
      - ./backups:/app/backups
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: python bot.py

  feed:
    build: .
    volumes:
      - ./backups:/app/backups
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: python feed_service.py