"""add_telegram_tables

Revision ID: 72cfce70e38d
Revises: 
Create Date: 2025-07-03 05:15:34.976286

"""
from typing import Sequence, Union
import sys
from pathlib import Path

from alembic import op
import sqlalchemy as sa

# Add the project root to Python path so we can import our custom types
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from src.database.models.telegram_models import JSONList


# revision identifiers, used by Alembic.
revision: str = '72cfce70e38d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invite_link', sa.String(length=500), nullable=True),
    sa.Column('member_count', sa.BigInteger(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', JSONList(), nullable=True),
    sa.Column('credibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reliability_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority_level', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_scam', sa.Boolean(), nullable=False),
    sa.Column('is_fake', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_telegram_channels_active_priority', 'telegram_channels', ['is_active', 'priority_level'], unique=False)
    op.create_index('idx_telegram_channels_category', 'telegram_channels', ['category'], unique=False)
    op.create_index('idx_telegram_channels_last_checked', 'telegram_channels', ['last_checked'], unique=False)
    op.create_index('idx_telegram_channels_region_country', 'telegram_channels', ['region', 'country'], unique=False)
    op.create_index('idx_telegram_channels_username', 'telegram_channels', ['username'], unique=False)
    op.create_table('channel_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('measurement_period', sa.String(length=50), nullable=False),
    sa.Column('total_messages', sa.BigInteger(), nullable=False),
    sa.Column('messages_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('peak_activity_hour', sa.BigInteger(), nullable=True),
    sa.Column('avg_views', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_forwards', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_replies', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('engagement_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_sentiment', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_urgency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_relevance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consistency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('member_count_start', sa.BigInteger(), nullable=True),
    sa.Column('member_count_end', sa.BigInteger(), nullable=True),
    sa.Column('member_growth_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('message_types', sa.JSON(), nullable=True),
    sa.Column('language_distribution', sa.JSON(), nullable=True),
    sa.Column('top_categories', JSONList(), nullable=True),
    sa.Column('processing_lag', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('uptime_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.channel_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'recorded_at', 'measurement_period', name='uq_channel_period_time')
    )
    op.create_index('idx_channel_metrics_activity', 'channel_metrics', ['activity_score'], unique=False)
    op.create_index('idx_channel_metrics_channel_recorded', 'channel_metrics', ['channel_id', 'recorded_at'], unique=False)
    op.create_index('idx_channel_metrics_period', 'channel_metrics', ['measurement_period'], unique=False)
    op.create_index('idx_channel_metrics_recorded_at', 'channel_metrics', ['recorded_at'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('from_username', sa.String(length=255), nullable=True),
    sa.Column('author_signature', sa.String(length=255), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('file_id', sa.String(length=500), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('forwards', sa.BigInteger(), nullable=True),
    sa.Column('replies', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('urgency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('categories', JSONList(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('detected_locations', JSONList(), nullable=True),
    sa.Column('detected_events', JSONList(), nullable=True),
    sa.Column('time_sensitivity', sa.String(length=50), nullable=True),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('forward_from_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('forward_from_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.channel_id'], ),
    sa.PrimaryKeyConstraint('message_id', 'channel_id'),
    sa.UniqueConstraint('message_id', 'channel_id', name='uq_message_channel')
    )
    op.create_index('idx_telegram_messages_categories', 'telegram_messages', ['categories'], unique=False)
    op.create_index('idx_telegram_messages_channel_date', 'telegram_messages', ['channel_id', 'date'], unique=False)
    op.create_index('idx_telegram_messages_date', 'telegram_messages', ['date'], unique=False)
    op.create_index('idx_telegram_messages_locations', 'telegram_messages', ['detected_locations'], unique=False)
    op.create_index('idx_telegram_messages_processed', 'telegram_messages', ['ai_processed', 'processed_at'], unique=False)
    op.create_index('idx_telegram_messages_sentiment', 'telegram_messages', ['sentiment_score'], unique=False)
    op.create_index('idx_telegram_messages_time_sensitivity', 'telegram_messages', ['time_sensitivity'], unique=False)
    op.create_index('idx_telegram_messages_urgency', 'telegram_messages', ['urgency_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telegram_messages_urgency', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_time_sensitivity', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_sentiment', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_processed', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_locations', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_date', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_channel_date', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_categories', table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index('idx_channel_metrics_recorded_at', table_name='channel_metrics')
    op.drop_index('idx_channel_metrics_period', table_name='channel_metrics')
    op.drop_index('idx_channel_metrics_channel_recorded', table_name='channel_metrics')
    op.drop_index('idx_channel_metrics_activity', table_name='channel_metrics')
    op.drop_table('channel_metrics')
    op.drop_index('idx_telegram_channels_username', table_name='telegram_channels')
    op.drop_index('idx_telegram_channels_region_country', table_name='telegram_channels')
    op.drop_index('idx_telegram_channels_last_checked', table_name='telegram_channels')
    op.drop_index('idx_telegram_channels_category', table_name='telegram_channels')
    op.drop_index('idx_telegram_channels_active_priority', table_name='telegram_channels')
    op.drop_table('telegram_channels')
    # ### end Alembic commands ###
