"""add news tables

Revision ID: ced5aaebd744
Revises: 72cfce70e38d
Create Date: 2025-09-04 16:55:11.475102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced5aaebd744'
down_revision: Union[str, Sequence[str], None] = '72cfce70e38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_cache',
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('update_frequency', sa.Integer(), nullable=False),
    sa.Column('last_success_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index(op.f('ix_feed_cache_source_priority'), 'feed_cache', ['source_priority'], unique=False)
    op.create_table('news_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=False),
    sa.Column('guid', sa.String(length=512), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feed_url', sa.String(length=1024), nullable=False),
    sa.Column('emoji1', sa.String(length=8), nullable=True),
    sa.Column('emoji2', sa.String(length=8), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('bias_category', sa.String(length=64), nullable=False),
    sa.Column('bias_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_news_entries_feed_url'), 'news_entries', ['feed_url'], unique=False)
    op.create_index(op.f('ix_news_entries_guid'), 'news_entries', ['guid'], unique=False)
    op.create_index(op.f('ix_news_entries_processed_date'), 'news_entries', ['processed_date'], unique=False)
    op.create_index(op.f('ix_news_entries_pub_date'), 'news_entries', ['pub_date'], unique=False)
    op.create_index(op.f('ix_news_entries_title'), 'news_entries', ['title'], unique=False)
    op.create_index('ix_news_pub_date_feed', 'news_entries', ['pub_date', 'feed_url'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', name='uq_tag_name_category')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_index('ix_article_tags_article_id', 'article_tags', ['article_id'], unique=False)
    # Unique constraint on telegram_messages already exists from previous migration
    # Skipping duplicate creation to avoid errors on upgrade
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_message_channel', 'telegram_messages', type_='unique')
    op.drop_index('ix_article_tags_article_id', table_name='article_tags')
    op.drop_table('article_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_news_pub_date_feed', table_name='news_entries')
    op.drop_index(op.f('ix_news_entries_title'), table_name='news_entries')
    op.drop_index(op.f('ix_news_entries_pub_date'), table_name='news_entries')
    op.drop_index(op.f('ix_news_entries_processed_date'), table_name='news_entries')
    op.drop_index(op.f('ix_news_entries_guid'), table_name='news_entries')
    op.drop_index(op.f('ix_news_entries_feed_url'), table_name='news_entries')
    op.drop_table('news_entries')
    op.drop_index(op.f('ix_feed_cache_source_priority'), table_name='feed_cache')
    op.drop_table('feed_cache')
    # ### end Alembic commands ###
