"""Database package initialization."""

from .models import (
    init_db,
    exists_in_db,
    get_db,
    cleanup_db,
    load_feed_cache,
    update_feed_cache,
    get_feed_metrics,
    get_source_priority,
    add_tag,
    tag_article,
    get_article_tags,
    search_articles_by_tags,
    store_article,
    init_briefing_tables,
    save_briefing,
    get_current_briefing,
    get_briefing_by_date,
    get_briefing_by_id,
    get_flash_items,
    update_briefing_metrics,
    get_regional_summary,
    get_news_in_timespan
)

__all__ = [
    'init_db',
    'exists_in_db',
    'get_db',
    'cleanup_db',
    'load_feed_cache',
    'update_feed_cache',
    'get_feed_metrics',
    'get_source_priority',
    'add_tag',
    'tag_article',
    'get_article_tags',
    'search_articles_by_tags',
    'store_article',
    'init_briefing_tables',
    'save_briefing',
    'get_current_briefing',
    'get_briefing_by_date',
    'get_briefing_by_id',
    'get_flash_items',
    'update_briefing_metrics',
    'get_regional_summary',
    'get_news_in_timespan'
]